// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BEEHapVdUvLfvUvlU6mvUoB6ejuchw0',
    appId: '1:834381607821:web:3e379d4c41e96504b603c4',
    messagingSenderId: '834381607821',
    projectId: 'patilefiredb',
    authDomain: 'patilefiredb.firebaseapp.com',
    storageBucket: 'patilefiredb.appspot.com',
    measurementId: 'G-5LGSBNQ3RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLPDaZ-Zn9Hb40bd_xNM6JRSJ6UZ0Zo4',
    appId: '1:834381607821:android:ba7ecf4794dc383eb603c4',
    messagingSenderId: '834381607821',
    projectId: 'patilefiredb',
    storageBucket: 'patilefiredb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9NsgNipASj-9_9swlVEk4ZOvIzCvAW-0',
    appId: '1:834381607821:ios:31577ae59152f423b603c4',
    messagingSenderId: '834381607821',
    projectId: 'patilefiredb',
    storageBucket: 'patilefiredb.appspot.com',
    iosClientId: '834381607821-mq92fjbp0bv1s0dktl9eaasgrvdjr9lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.patile',
  );
}
